name: Ansible/Python Setup
description: Setup Python, install Ansible, dependencies, prepare inventory, and set up SSH key
inputs:
  ssh-private-key:
    description: "SSH key for EC2 instances"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up SSH key
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh-private-key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ansible
      shell: bash

    - name: Install Ansible Galaxy collections/roles
      run: |
        if [ -f ansible/requirements.yml ]; then
          ansible-galaxy install -r ansible/requirements.yml --force
        fi
      shell: bash

    - name: Prepare dynamic inventory
      run: |
        chmod +x ansible/inventory_script.py
        python3 ansible/inventory_script.py > inventory.yml
      shell: bash
