name: Ansible/Python Setup
description: Setup Python, install Ansible, dependencies, and prepare inventory
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ansible
      shell: bash

    - name: Install Ansible Galaxy collections/roles
      run: |
        if [ -f ansible/requirements.yml ]; then
          ansible-galaxy install -r ansible/requirements.yml --force
        fi
      shell: bash

    - name: Prepare dynamic inventory
      run: |
        chmod +x ansible/inventory_script.py
        python3 ansible/inventory_script.py > inventory.yml
      shell: bash
