name: Terragrunt Plan

on:
  push:
    paths:
      - "terraform/**"
      - ".github/workflows/terragrunt.yml"
  pull_request:

jobs:
  terragrunt-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Set up Terragrunt
        run: |
          TG_VERSION=0.58.14
          if ! command -v terragrunt >/dev/null 2>&1 || [ "$(terragrunt --version | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')" != "v${TG_VERSION}" ]; then
            curl -sSL -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64
            chmod +x terragrunt
            sudo mv terragrunt /usr/local/bin/terragrunt
          fi
          terragrunt --version

      - name: Terragrunt plan
        run: |
          cd terraform/live/eu-west-1/ec2/flask-backend
          terragrunt plan
