name: "Terragrunt Setup"
description: "Install Terraform and Terragrunt"
runs:
  using: "composite"
  steps:
    - name: AWS Credentials Setup
      uses: ../aws-setup

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Set up Terragrunt
      shell: bash
      run: |
        TG_VERSION=0.58.14
        if ! command -v terragrunt >/dev/null 2>&1 || [ "$(terragrunt --version | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')" != "v${TG_VERSION}" ]; then
          curl -sSL -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/terragrunt
        fi
        terragrunt --version
