name: "AWS Credentials Setup"
description: "Configure AWS credentials for GitHub Actions"
inputs:
  aws-access-key-id:
    description: "AWS access key ID"
    required: true
  aws-secret-access-key:
    description: "AWS secret access key"
    required: true
  aws-region:
    description: "AWS region"
    required: false
    default: eu-west-1
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}