---
- name: Distribute SSH public key to bastion
  hosts: bastion_hosts
  become: true
  vars:
    ssh_user: ubuntu
    ansible_user: ubuntu
  collections:
    - community.aws
  tasks:
    - name: Fetch SSH public key from AWS SSM Parameter Store (locally)
      community.aws.ssm_parameter:
        name: /flask-demo/ssh/flask-demo-key
        decryption: yes
        region: eu-west-1
        state: present
      register: ssh_key
      delegate_to: localhost
      run_once: true

    - name: Ensure ~/.ssh directory exists for the SSH user
      ansible.builtin.file:
        path: /home/{{ ssh_user }}/.ssh
        state: directory
        mode: "0700"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"

    - name: Write SSH public key to authorized_keys
      ansible.builtin.copy:
        content: "{{ ssh_key.parameter.value }}"
        dest: /home/{{ ssh_user }}/.ssh/authorized_keys
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: "0600"
