- name: Fetch SSH key from SSM using lookup plugin
  hosts: localhost
  gather_facts: no
  collections:
    - amazon.aws
  become: false
  vars:
    ssm_parameter_name: "/flask-demo/ssh/flask-demo-key"
    region: "eu-west-1"
    ssh_key_path: "./tmp/flask-demo-key.pem"

  tasks:
    - file:
        path: "{{ ssh_key_path | dirname }}"
        state: directory
        mode: "0700"

    - set_fact:
        ssh_private_key: "{{ lookup('amazon.aws.aws_ssm', ssm_parameter_name, region=region, decrypt=true) }}"

    - copy:
        content: "{{ ssh_private_key }}"
        dest: "{{ ssh_key_path }}"
        mode: "0600"

    - debug:
        msg: "SSH key saved to {{ ssh_key_path }}"
