---
- name: Setup Nginx configuration (bastion_hosts)
  hosts: bastion_hosts
  become: true
  vars:
    ansible_user: ec2-user
    flask_port: 5001
    backend_instances:
      - ip: "{{ hostvars['flask-backend-1'].ansible_host }}"
        port: 5001
      - ip: "{{ hostvars['flask-backend-2'].ansible_host }}"
        port: 5001
    active_backends: "{{ backend_instances }}"
    ansible_python_interpreter: /usr/bin/python3.8
  roles:
    - nginx
  gather_facts: false
  tasks:
    - name: Apply nginx role
      ansible.builtin.include_role:
        name: nginx
      vars:
        active_backends: "{{ active_backends }}"

    - name: Debug configuration
      ansible.builtin.debug:
        msg: "Nginx configured to proxy to backends at {{ active_backends | map(attribute='ip') | list }}:{{ flask_port }}"
      when: ansible_debug | default(false) | bool
