---
- name: Configure Bastion
  hosts: bastion_hosts
  become: true
  vars:
    ansible_user: ubuntu
  roles:
    - nginx

- name: Configure NAT instance
  hosts: gateway_hosts
  become: true
  vars:
    ansible_user: ec2-user
  roles:
    - nat_instance

- name: Configure Backend (Flask app servers)
  hosts: app_servers
  become: true
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - backend
