---
- name: Verify NAT instance connectivity
  hosts: gateway_hosts
  gather_facts: no
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Ping external IP (8.8.8.8) from NAT instance
      ansible.builtin.command:
        cmd: ping -c 3 8.8.8.8
      register: ping_result
      ignore_errors: yes

    - name: Fail if NAT cannot reach internet
      ansible.builtin.fail:
        msg: "NAT instance cannot reach internet."
      when: ping_result.rc != 0
