---
- name: Install required packages (docker)
  apt:
    name:
      - docker.io
    state: present
    update_cache: yes

- name: Enable and start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add ubuntu to docker group (to allow non-root Docker usage)
  user:
    name: ubuntu
    group: docker
    append: yes

- name: Ensure the Docker service is started
  service:
    name:
