---
- name: Install required packages
  ansible.builtin.yum:
    name:
      - docker
      - git
    state: present
  become: true

- name: Copy backend application files
  ansible.builtin.copy:
    src: ../../app/
    dest: /opt/flask/
    owner: ec2-user
    group: ec2-user
    mode: "0755"
  become: true

- name: Build Docker image for backend
  community.docker.docker_image:
    name: flask-app-image
    build:
      path: /opt/flask/
    state: present
  become: true

- name: Start backend Docker container
  community.docker.docker_container:
    name: flask-app
    image: flask-app-image
    state: started
    restart_policy: always
    published_ports:
      - "5001:5001"
  become: true
