---
- name: Debug playbook directory and source paths
  ansible.builtin.debug:
    msg: "playbook_dir: {{ playbook_dir }}, Source path for {{ item }}: {{ playbook_dir }}/../../app/{{ item }}"
  loop:
    - app.py
    - Dockerfile
  when: ansible_debug | default(true) | bool

- name: Ensure Flask app directory exists
  ansible.builtin.file:
    path: /opt/flask
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: "0755"

- name: Copy Flask app files
  ansible.builtin.copy:
    src: "/Users/grond/repo/flask-api-demo/app/{{ item }}"
    dest: /opt/flask/{{ item }}
    owner: ec2-user
    group: ec2-user
    mode: "0644"
  loop:
    - app.py
    - Dockerfile

- name: Build Flask Docker image
  community.docker.docker_image:
    name: flask-app-image
    tag: latest
    source: build
    build:
      path: /opt/flask
      dockerfile: Dockerfile
    state: present
  register: build_image

- name: Run Flask app in Docker
  community.docker.docker_container:
    name: flask-app
    image: flask-app-image:latest
    state: started
    restart_policy: always
    ports:
      - "5001:5001"
    env:
      FLASK_ENV: dev

- name: Debug Docker container status
  ansible.builtin.command: docker ps -f name=flask-app
  register: docker_status
  changed_when: false

- name: Show Docker container status
  ansible.builtin.debug:
    msg: "Docker container status: {{ docker_status.stdout_lines }}"
  when: ansible_debug | default(true) | bool