---
- name: Install required packages (docker)
  apt:
    name:
      - docker.io
    state: present
    update_cache: yes

- name: Enable and start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add ubuntu to docker group (to allow non-root Docker usage)
  user:
    name: ubuntu
    group: docker
    append: yes

- name: Ensure the Docker service is started
  service:
    name: docker
    state: started
    enabled: yes

- name: Pull the latest Docker image (e.g., Flask app)
  docker_image:
    name: "{{ flask_image }}"
    source: pull

- name: Run the Flask app container
  docker_container:
    name: flask_app
    image: "{{ flask_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ flask_ports }}" # Using flask_ports as a variable
