---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure python3-pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install boto3 and botocore Python packages
  ansible.builtin.pip:
    name:
      - boto3
      - botocore
    executable: pip3

- name: Ensure www-data user exists
  ansible.builtin.user:
    name: www-data
    state: present
    system: true
    create_home: false

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  become: true

- name: Ensure Nginx configuration directory exists
  ansible.builtin.file:
    path: /etc/nginx
    state: directory
    mode: "0755"
  become: true

- name: Ensure Nginx conf.d directory exists
  ansible.builtin.file:
    path: /etc/nginx/conf.d
    state: directory
    mode: "0755"
  become: true

- name: Configure Nginx as reverse proxy
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
    validate: "nginx -t -c %s"
  become: true
  notify: Restart Nginx

- name: Generate Nginx upstream configuration
  ansible.builtin.template:
    src: upstream.conf.j2
    dest: /etc/nginx/conf.d/flask-backend.conf
    mode: "0644"
  become: true
  notify: Reload Nginx

- name: Ensure Nginx is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  become: true
