name: Ansible Deploy Chain

on:
  push:
    branches:
      - '**'
    paths:
      - 'app/**'
      - 'ansible/roles/**'
      - 'ansible/playbooks/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      nat: ${{ steps.filter.outputs.nat }}
      nginx: ${{ steps.filter.outputs.nginx }}
      all: ${{ steps.filter.outputs.all }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'app/**'
              - 'ansible/roles/backend/**'
              - 'ansible/playbooks/deploy_backend.yml'
            nat:
              - 'ansible/roles/nat_instance/**'
              - 'ansible/playbooks/deploy_nat.yml'
            nginx:
              - 'ansible/roles/nginx/**'
              - 'ansible/playbooks/deploy_nginx.yml'
            all:
              - 'ansible/playbooks/deploy_all.yml'
              - 'ansible/roles/**'
              - 'terraform/**'

  deploy-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ansible-setup
      - run: ansible-playbook -i inventory.yml ansible/playbooks/deploy_backend.yml

  deploy-nat:
    needs: detect-changes
    if: needs.detect-changes.outputs.nat == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ansible-setup
      - run: ansible-playbook -i inventory.yml ansible/playbooks/deploy_nat.yml

  deploy-nginx:
    needs: detect-changes
    if: needs.detect-changes.outputs.nginx == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ansible-setup
      - run: ansible-playbook -i inventory.yml ansible/playbooks/deploy_nginx.yml

  deploy-all:
    needs: detect-changes
    if: needs.detect-changes.outputs.all == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ansible-setup
      - run: ansible-playbook -i inventory.yml ansible/playbooks/deploy_all.yml