name: Deploy with Ansible
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y docker.io

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Start SSH agent and add bastion key
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Ansible collections and roles
        run: |
          ansible-galaxy collection install community.docker
          ansible-galaxy install geerlingguy.docker

      - name: Generate inventory
        env:
          AWS_REGION: eu-west-1
        run: |
          chmod +x inventory_script.py
          python3 inventory_script.py > inventory.yml
          cat inventory.yml

      - name: Run Ansible playbook
        run: ansible-playbook -i inventory.yml playbook.yml -v
