name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'        # Run on push to any branch
  pull_request:
    branches:
      - '**'        # Run build/test on PR open/update for any branch
    types:
      - opened
      - synchronize
      - reopened
      - closed        # Detect PR close event (merge or close)

jobs:
  build_and_test:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: cp .env.example .env

      - run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV  

      - run: pytest -v tests/test_app.py

  deploy:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: |
          sudo apt-get update -y
          sudo apt-get remove -y containerd containerd.io
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg
          echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update -y
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: |
          mkdir -p $HOME/.ansible/collections
          export ANSIBLE_GALAXY_COLLECTIONS_PATH=$HOME/.ansible/collections
          ansible-galaxy collection install community.docker
          ansible-galaxy install geerlingguy.docker

      - env:
          AWS_REGION: eu-west-1
        run: |
          chmod +x ansible/inventory_script.py
          python3 ansible/inventory_script.py > inventory.yml
          cat inventory.yml

      - run: ansible-playbook -i inventory.yml ansible/playbooks/site.yml --limit app_servers -v
