name: Terragrunt Apply

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '**/*.hcl'
      - '.github/workflows/terragrunt-apply.yml'
      - 'terraform/**/main.tf'
      - 'terraform/**/terragrunt.hcl'
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - '**/*.tf'
      - '**/*.hcl'
      - '.github/workflows/terragrunt-apply.yml'
      - 'terraform/**/main.tf'
      - 'terraform/**/terragrunt.hcl'

jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup AWS credentials
        uses: ./.github/actions/aws-setup
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terragrunt
        uses: ./.github/actions/terragrunt-setup

      - name: Cache Terragrunt cache
        uses: actions/cache@v4
        with:
          path: terraform/.terragrunt-cache
          key: ${{ runner.os }}-terragrunt-${{ hashFiles('terraform/**/*.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terragrunt-

      - name: Find changed terragrunt directories cumulatively since branch divergence
        id: changed-dirs
        shell: bash
        run: |
          set -e

          # Fetch main branch to get up-to-date refs
          git fetch origin main

          # Determine base SHA for diff:
          # For PR merge events, use the merge commit's parent 1 (main branch before merge)
          # For push events, use merge-base between HEAD and origin/main

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE_SHA=$(git rev-parse HEAD^1)
          else
            BASE_SHA=$(git merge-base HEAD origin/main)
          fi

          echo "Base commit for diff: $BASE_SHA"

          CHANGED_FILES=$(git diff --name-only "$BASE_SHA" HEAD | grep '^terraform/.*\.\(tf\|hcl\)$' || true)

          MODULE_CHANGED_FILES=$(echo "$CHANGED_FILES" | grep '^terraform/modules/' || true)
          TERRAGRUNT_CHANGED_FILES=$(echo "$CHANGED_FILES" | grep -v '^terraform/modules/' || true)

          DIRS=""

          for file in $TERRAGRUNT_CHANGED_FILES; do
            d=$(dirname "$file")
            while [[ "$d" != "terraform" && "$d" != "." ]]; do
              if [[ -f "$d/terragrunt.hcl" ]]; then
                DIRS="$DIRS $d"
                break
              fi
              d=$(dirname "$d")
            done
          done

          if [[ -n "$MODULE_CHANGED_FILES" ]]; then
            MODULE_NAMES=$(echo "$MODULE_CHANGED_FILES" | awk -F/ '{print $3}' | sort -u)
            ALL_TG_DIRS=$(find terraform -type f -name terragrunt.hcl -exec dirname {} \;)

            for tgdir in $ALL_TG_DIRS; do
              for module_name in $MODULE_NAMES; do
                if grep -q "\.\.//modules/$module_name" "$tgdir/terragrunt.hcl"; then
                  DIRS="$DIRS $tgdir"
                  break
                fi
              done
            done
          fi

          DIRS=$(echo "$DIRS" | tr ' ' '\n' | sort -u | tr '\n' ' ' | xargs)

          echo "dirs=$DIRS" >> "$GITHUB_OUTPUT"

      - name: Run Terragrunt apply in changed directories
        if: steps.changed-dirs.outputs.dirs != ''
        run: |
          IFS=' ' read -r -a dirs <<< "${{ steps.changed-dirs.outputs.dirs }}"
          for d in "${dirs[@]}"; do
            echo "==> Running terragrunt apply in $d"
            (cd "$d" && terragrunt init --terragrunt-non-interactive && terragrunt apply --terragrunt-non-interactive -auto-approve)
          done
