name: Terragrunt Apply

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terragrunt-apply.yml'

jobs:
  terragrunt-apply-vpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: AWS Credentials Setup
        uses: ./.github/actions/aws.yml

      - uses: ./.github/actions/terragrunt-setup.yml

      - name: Cache Terragrunt cache
        uses: actions/cache@v4
        with:
          path: |
            terraform/.terragrunt-cache
          key: ${{ runner.os }}-terragrunt-${{ hashFiles('terraform/**/*.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terragrunt-

      - name: Terragrunt Init (VPC)
        working-directory: terraform/live/eu-west-1/flask-demo-vpc
        run: terragrunt init

      - name: Terragrunt Apply (VPC)
        working-directory: terraform/live/eu-west-1/flask-demo-vpc
        run: terragrunt apply -auto-approve