name: Terragrunt Apply

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terragrunt-apply.yml'

jobs:
  terragrunt-apply-vpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Install Terragrunt
        run: |
          TG_VERSION=0.58.14
          wget -qO- https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64 > terragrunt
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/terragrunt
          terragrunt --version

      - name: Cache Terragrunt cache
        uses: actions/cache@v4
        with:
          path: |
            terraform/.terragrunt-cache
          key: ${{ runner.os }}-terragrunt-${{ hashFiles('terraform/**/*.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terragrunt-

      - name: Terragrunt Init (VPC)
        working-directory: terraform/live/eu-west-1/flask-demo-vpc
        run: terragrunt init

      - name: Terragrunt Apply (VPC)
        working-directory: terraform/live/eu-west-1/flask-demo-vpc
        run: terragrunt apply -auto-approve