name: Terragrunt Plan

on:
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/terragrunt-plan.yml'
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terragrunt-plan.yml'

jobs:
  terragrunt-plan-vpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: AWS Credentials Setup
        uses: ./.github/actions/aws-setup

      - uses: ./.github/actions/terragrunt-setup

      - name: Cache Terragrunt cache
        uses: actions/cache@v4
        with:
          path: |
            terraform/.terragrunt-cache
          key: ${{ runner.os }}-terragrunt-${{ hashFiles('terraform/**/*.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terragrunt-

      - name: Terragrunt Init (VPC)
        working-directory: terraform/live/eu-west-1/flask-demo-vpc
        run: terragrunt init

      - name: Terragrunt Plan (VPC)
        working-directory: terraform/live/eu-west-1/flask-demo-vpc
        run: terragrunt plan