name: Terragrunt Plan

on:
  push:
    paths:
      - '**/*.tf'
      - '**/*.hcl'
      - '.github/workflows/terragrunt-plan.yml'
      - 'terraform/**/main.tf'
      - 'terraform/**/terragrunt.hcl'
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.hcl'
      - '.github/workflows/terragrunt-plan.yml'
      - 'terraform/**/main.tf'
      - 'terraform/**/terragrunt.hcl'
  workflow_dispatch:

jobs:
  terragrunt-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/aws-setup
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: ./.github/actions/terragrunt-setup

      - name: Cache Terragrunt cache
        uses: actions/cache@v4
        with:
          path: |
            terraform/.terragrunt-cache
          key: ${{ runner.os }}-terragrunt-${{ hashFiles('terraform/**/*.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terragrunt-

      - name: Find changed terragrunt directories
        id: changed-dirs
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref || 'main' }} --depth=1 || true
          # Find changed files under terraform/
          CHANGED=$(git diff --name-only ${{ github.event.pull_request.base.sha || 'origin/main' }} HEAD | grep '^terraform/' | xargs -n1 dirname | sort -u)
          # Only keep directories containing a terragrunt.hcl
          DIRS=""
          for d in $CHANGED; do
            if [ -f "$d/terragrunt.hcl" ]; then
              DIRS="$DIRS $d"
            fi
          done
          echo "dirs=$DIRS" >> $GITHUB_OUTPUT

      - name: Debug Terragrunt remote state key
        if: steps.changed-dirs.outputs.dirs != ''
        run: |
          for d in ${{ steps.changed-dirs.outputs.dirs }}; do
            echo "==== $d ===="
            cd $d
            echo "PWD: $(pwd)"
            echo "Terragrunt config path: $(realpath terragrunt.hcl)"
            terragrunt terragrunt-info | grep '"remote_state":' -A 20
            cd -
          done

      - name: Terragrunt plan in changed directories
        if: steps.changed-dirs.outputs.dirs != ''
        run: |
          for d in ${{ steps.changed-dirs.outputs.dirs }}; do
            echo "Running terragrunt plan in $d"
            (cd $d && terragrunt init && terragrunt plan)
          done