name: Terragrunt Apply

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '**/*.hcl'
      - '.github/workflows/terragrunt-apply.yml'
      - 'terraform/**/main.tf'
      - 'terraform/**/terragrunt.hcl'
  workflow_dispatch:

jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/aws-setup
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: ./.github/actions/terragrunt-setup

      - name: Cache Terragrunt cache
        uses: actions/cache@v4
        with:
          path: terraform/.terragrunt-cache
          key: ${{ runner.os }}-terragrunt-${{ hashFiles('terraform/**/*.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terragrunt-

      - name: Find changed terragrunt directories
        id: dirs-to-apply
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
          else
            BASE_SHA=$(git rev-parse HEAD^)
          fi

          echo "Using base SHA: $BASE_SHA"

          # Find changed .tf and .hcl files under terraform/
          CHANGED_FILES=$(git diff --name-only "$BASE_SHA" HEAD | grep '^terraform/.*\.\(tf\|hcl\)$' || true)

          DIRS=""
          for file in $CHANGED_FILES; do
            d=$(dirname "$file")
            # Walk up folders until we find a terragrunt.hcl or reach root terraform dir
            while [ "$d" != "terraform" ] && [ "$d" != "." ]; do
              if [ -f "$d/terragrunt.hcl" ]; then
                DIRS="$DIRS $d"
                break
              fi
              d=$(dirname "$d")
            done
          done

          # Remove duplicates and exclude terraform/live root explicitly
          DIRS=$(echo "$DIRS" | tr ' ' '\n' | sort -u | grep -v '^terraform/live$' || true)

          echo "dirs=$DIRS" >> "$GITHUB_OUTPUT"

      - name: Debug Terragrunt directories to apply
        if: steps.dirs-to-apply.outputs.dirs != ''
        run: |
          IFS=' ' read -r -a dirs <<< "${{ steps.dirs-to-apply.outputs.dirs }}"
          echo "Terragrunt will apply these directories:"
          for d in "${dirs[@]}"; do
            echo "  - $d"
          done

      - name: Terragrunt apply in changed directories
        if: steps.dirs-to-apply.outputs.dirs != ''
        run: |
          IFS=' ' read -r -a dirs <<< "${{ steps.dirs-to-apply.outputs.dirs }}"
          for d in "${dirs[@]}"; do
            if [ ! -f "$d/terragrunt.hcl" ]; then
              echo "Skipping $d because terragrunt.hcl not found"
              continue
            fi
            echo "==> Running terragrunt apply in $d"
            (cd "$d" && terragrunt init && terragrunt apply -auto-approve)
          done
