name: Terragrunt Apply

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for full git history and diff

      - uses: ./.github/actions/aws-setup
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: ./.github/actions/terragrunt-setup

      - name: Cache Terragrunt cache
        uses: actions/cache@v4
        with:
          path: terraform/.terragrunt-cache
          key: ${{ runner.os }}-terragrunt-${{ hashFiles('terraform/**/*.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terragrunt-

      - name: Find changed terragrunt directories (cumulative since branch divergence)
        id: changed-dirs
        shell: bash
        run: |
          set -e

          # Fetch main branch to ensure up-to-date refs
          git fetch origin main

          # Find merge base between current HEAD and main branch
          BASE_SHA=$(git merge-base HEAD origin/main)
          echo "Merge base commit (branch divergence point): $BASE_SHA"

          # Get changed terraform files cumulatively since branch divergence
          CHANGED_FILES=$(git diff --name-only "$BASE_SHA" HEAD | grep '^terraform/.*\.\(tf\|hcl\)$' || true)

          MODULE_CHANGED_FILES=$(echo "$CHANGED_FILES" | grep '^terraform/modules/' || true)
          TERRAGRUNT_CHANGED_FILES=$(echo "$CHANGED_FILES" | grep -v '^terraform/modules/' || true)

          DIRS=""

          # Add stacks directly changed outside modules
          for file in $TERRAGRUNT_CHANGED_FILES; do
            d=$(dirname "$file")
            while [[ "$d" != "terraform" && "$d" != "." ]]; do
              if [[ -f "$d/terragrunt.hcl" ]]; then
                DIRS="$DIRS $d"
                break
              fi
              d=$(dirname "$d")
            done
          done

          # Add stacks referencing changed modules
          if [[ -n "$MODULE_CHANGED_FILES" ]]; then
            MODULE_NAMES=$(echo "$MODULE_CHANGED_FILES" | awk -F/ '{print $3}' | sort -u)

            ALL_TG_DIRS=$(find terraform -type f -name terragrunt.hcl -exec dirname {} \;)

            for tgdir in $ALL_TG_DIRS; do
              for module_name in $MODULE_NAMES; do
                if grep -q "\.\.//modules/$module_name" "$tgdir/terragrunt.hcl"; then
                  DIRS="$DIRS $tgdir"
                  break
                fi
              done
            done
          fi

          # Remove duplicates and trim whitespace
          DIRS=$(echo "$DIRS" | tr ' ' '\n' | sort -u | tr '\n' ' ' | xargs)

          echo "dirs=$DIRS" >> "$GITHUB_OUTPUT"

      - name: Debug Terragrunt directories to apply
        if: false
        run: |
          IFS=' ' read -r -a dirs <<< "${{ steps.changed-dirs.outputs.dirs }}"
          echo "Terragrunt will apply these directories:"
          for d in "${dirs[@]}"; do
            echo "  - $d"
          done

      - name: Terragrunt apply in changed directories
        if: steps.changed-dirs.outputs.dirs != ''
        shell: bash
        run: |
          set -e
          IFS=' ' read -r -a dirs <<< "${{ steps.changed-dirs.outputs.dirs }}"
          for d in "${dirs[@]}"; do
            if [[ ! -f "$d/terragrunt.hcl" ]]; then
              echo "Skipping $d because terragrunt.hcl not found"
              continue
            fi
            echo "==> Running terragrunt apply in $d"
            (cd "$d" && terragrunt init --terragrunt-non-interactive && terragrunt apply -auto-approve --terragrunt-non-interactive)
          done
